config/routes.rb
Rails.application.routes.draw do
  #GET /about
  get "about", to: "about#index" #the about controller with index action

  #GET / :main
  root to: "main#index"
  # get "/", to: "main#index" #the main/home controller with the index action

  #For sign up page
  get "sign_up", to: "registrations#new"

  #For creating a user
  post "sign_up", to: "registrations#create"

  #For logging out a user
  delete 'logout', to: "sessions#destroy"

  #For the sign in page
  get 'sign_in', to: "sessions#new"

  #For the user to sign in
  post "sign_in", to: 'sessions#create'

  #For password edit
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  #For Forgot Password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  #For From email
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  #For omniauth callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"


  #To manage twitter account[s]
  #resources performs CRUD routes
  resources :twitter_accounts
  resources :tweets
 



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  #validation
  validates :body, length: {minimum: 1, maximum: 280}
  validates :published_at, presence: true

  #after it is in memory or initializes, set default values
  after_initialize do 
    #set the default value of the publish at
    self.published_at ||= 24.hours.from_now
  end

  #if the tweet is published
  def published?
    tweet_id? #to check if there is a tweet_id and return boolean
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    #make sure the user is logged in
    before_action :reqiure_user_logged_in!
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]

    
    def index
       @tweets = Current.user.tweets 
    end  

    def new
        @tweet = Tweet.new
    end
    
    def create 
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
            redirect_to tweets_path, notice: "Your Tweet was scheduled successfully"
        else
            render :new
        end
    end

    #to load the editing page
    def edit 

    end

    #to update the tweet in the db    
    def update
        if @tweet.update(tweet_params)
            redirect_to tweets_path, notice: "Your Tweet was updated successfully"
        else
            render :edit
        end
    end

    #to delete a tweet 
    def destroy
        @tweet.destroy
        redirect_to tweets_path, alert: "Your Tweet was unscheduled"
    end
    
    


    private

    def tweet_params
        params.require(:tweet).permit(:twitter_account_id, :body, :published_at)
    end
    
    def set_tweet
        @tweet = Current.user.tweets.find(params[:id])
    end
    
end

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
<%= render "shared/form_errors", form: form %>


    <div class='mb-3'>
        <%= form.label :twitter_account_id %>
        <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
        <p>Add another account? <%= link_to 'Connect', "/auth/twitter", method: :post %> </p>
    </div>

    <div class='mb-3'>
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control" %>
    </div>

    <div class="mb-3">
        <%= form.label :publish_at %>
        <div class="form-control">
            <%= form.datetime_select :publish_at %>
        </div>
    </div>

    <div class="d-flex flex-row">
        <% if form.object.persisted? %>
            <div>
                <%= button_to 'Update Tweet', form.object, method: :patch, class: 'btn btn-primary' %>
            </div>
        <% else %>
            <div>
                <%= form.button "Schedule", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
    

    <%# if the data is stored in the db, then delete %>
    <% if form.object.persisted? %>
        <%= button_to 'Delete', form.object, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
    <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
    <%= tweet.body %>

    <div class='me-4'>
        <%= image_tag tweet.twitter_account.image, class: 'rounded-circle' %>
        <%= tweet.twitter_account.name %>
        <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>

        <% if tweet.published? %>
            <%= link_to 'View Tweet', "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}" %>
        <% else %>
            Scheduled For: <%= l tweet.published_at, format: :long %> <%# the l is a helper for the time and date and the format is the format you want it in ie short/long %>

            <%= link_to 'Edit Tweet', edit_tweet_path(tweet) %>
        <% end %>
    </div>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>
<%# the above is component in js and the second arg is what you want to pass as prop in js to the component %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Tweets</h1>

<%# if there is a twitter account %>
<% if Current.user.twitter_accounts.any? %>
    <%= link_to 'Schedule a Tweet', new_tweet_path, class: "btn btn-primary" %>
<% end %>  
</div>

<%# If there are no twitter accounts %>
<% if Current.user.twitter_accounts.none? %>
    <%= link_to "Connect a Twitter Account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
<% end %>

<%# render a partial(component) from _tweet.html.erb %>
<%= render @tweets %> 

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%# form %>
<%= render "form", tweet: @tweet %>
<%# the above is component in js and the second arg is what you want to pass as prop in js to the component %>