config/routes.rb
Rails.application.routes.draw do
  #GET /about
  get "about", to: "about#index" #the about controller with index action

  #GET / :main
  root to: "main#index"
  # get "/", to: "main#index" #the main/home controller with the index action

  #For sign up page
  get "sign_up", to: "registrations#new"

  #For creating a user
  post "sign_up", to: "registrations#create"

  #For logging out a user
  delete 'logout', to: "sessions#destroy"

  #For the sign in page
  get 'sign_in', to: "sessions#new"

  #For the user to sign in
  post "sign_in", to: 'sessions#create'

  #For password edit
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  #For Forgot Password
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  #For From email
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  #For omniauth callback
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"


  #To manage twitter account[s]
  #resources performs CRUD routes
  resources :twitter_accounts
  resources :tweets
 



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<%
=begin%>
  The flash sends a message to the use and disappers after the next request, that is why we have the if statement
<%
=end%>
<% if flash[:notice] %>
    <div class='alert alert-info mt-4' role='alert'>
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class='alert alert-warning mt-4' role='alert'>
    <%= flash[:alert] %>
    </div>
<%end %>

app/views/shared/_form_errors.html.erb
<%# for errors %>
<% if form.object.errors.any? %>
    <div class='alert alert-danger'>
        <% form.object.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Navbar", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
      <%= link_to "Tweets", tweets_path, class:'nav-link active' %> 
        <%# router helper- linking to about dynamically the "about_path" is the link url %>
      <%= link_to "About", about_path, class:"nav-link" %>

      <%= link_to 'Twitter Accounts', twitter_accounts_path, class: "nav-link" %>
      </div>

      <div class='navbar-nav ms-auto mb-2 mb-lg-0'>
      <%# if a user is signed in %>
        <% if Current.user %>
          <div class='nav-item'>
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </div>
          <div>
            <%= button_to "logout", logout_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
          </div>

        <%# sign up or sign in a user %>
        <% else %>
          <div class='nav-item'>
            <%= link_to 'Sign Up', sign_up_path, class: "nav-link" %>
          </div>
          <div class='nav-item'>
            <%= link_to 'Log In', sign_in_path, class: "nav-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>